# Generated by Django 4.2.6 on 2023-10-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_my_users_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_Users',
        ),
    ]
