# Generated by Django 4.2.6 on 2023-10-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_delete_my_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
